const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync('insurance.js','utf8');const ctx=vm.createContext({crypto:require('crypto').webcrypto,TextEncoder,Uint8Array,Blob,Intl});
vm.runInContext(source.slice(0,source.indexOf("$('#biFile').onchange"))+"globalThis.test={amount,paid,choosePlans,insurancePlan,buildVietQrPayload,crc16ccitt,insurancePdf};})();",ctx);const t=ctx.test;
(async()=>{
assert.equal(t.amount('631.800'),631800);assert.equal(t.amount('631,800'),631800);assert.equal(t.amount('0'),0);for(const v of ['','1.5','-100','abc'])assert.throws(()=>t.amount(v));assert.equal(t.paid('Đã nộp'),true);assert.equal(t.paid('Chưa nộp'),false);assert.throws(()=>t.paid('Một phần'));
const row={code:'001',name:'DỮ LIỆU THỬ',className:'6A1',health:631800,body:150000};assert.deepEqual(Array.from(t.choosePlans(row).options,o=>o.amount),[631800,781800]);assert.equal(t.choosePlans({...row,hp:true}).options[0].label,'Chỉ nộp BHTT');assert.equal(t.choosePlans({...row,bp:true}).options[0].label,'Chỉ nộp BHYT');assert.equal(t.choosePlans({...row,hp:true,bp:true}).options.length,0);assert.equal(t.choosePlans({...row,health:0}).options.length,1);
const e=t.choosePlans(row),config={bin:'970418',accountNumber:'0000000000',accountName:'KIEM THU'};const p=await t.insurancePlan(e.student,e.options[1],config,'Trường A|2026');assert.equal(p.remark,(await t.insurancePlan(e.student,e.options[1],config,'Trường A|2026')).remark);assert.notEqual(p.remark,(await t.insurancePlan(e.student,e.options[1],config,'Trường B|2026')).remark);
const payload=t.buildVietQrPayload(config,781800,p.remark);function tags(s){let i=0,out={};while(i<s.length){const id=s.slice(i,i+2),n=Number(s.slice(i+2,i+4));assert.ok(Number.isInteger(n)&&i+4+n<=s.length);out[id]=s.slice(i+4,i+4+n);i+=n+4;}assert.equal(i,s.length);return out;}const fields=tags(payload);assert.equal(fields['60'],'VIETNAM');assert.equal(fields['54'],'781800');assert.equal(tags(fields['62'])['08'],p.remark);assert.equal(tags(tags(fields['38'])['01'])['01'],config.accountNumber);assert.equal(fields['63'],t.crc16ccitt(payload.slice(0,-4)));console.log('PASS: amount/status validation, four states, per-school stable codes, QR TLV lengths, recipient, total and CRC');
})().catch(e=>{console.error(e);process.exitCode=1});
