const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {groupRows,paginate,amount}=require('../choice-engine.js');
const base={code:'00125',name:'HỌC SINH MẪU',className:'6A1',group:'BAOHIEM26',bin:'970418',accountName:'TAI KHOAN MAU'};
const rows=[{...base,paymentCode:'HG26BH00125A',label:'Chỉ BHYT',amount:'631.800',accountNumber:'000000000001',remark:'HG26BH00125A',includes:'BHYT'}, {...base,paymentCode:'HG26BH00125B',label:'BHYT + BHTT',amount:781800,accountNumber:'000000000002',remark:'HG26BH00125B',includes:'BHYT + BHTT'}];
const groups=groupRows(rows);assert.equal(groups.length,1);assert.equal(groups[0].options.length,2);assert.deepEqual(groups[0].options.map(o=>o.amount),[631800,781800]);assert.equal(groups[0].options[0].accountNumber,'000000000001');assert.equal(groups[0].options[1].paymentCode,'HG26BH00125B');assert.equal(paginate(groups).length,1);
assert.throws(()=>groupRows([rows[0],rows[0]]),/Trùng mã thu/);assert.throws(()=>groupRows([rows[0],{...rows[1],name:'KHÁC'}]),/mâu thuẫn/);assert.throws(()=>groupRows([{...rows[0],code:''}]),/mã học sinh/);assert.throws(()=>groupRows([{...rows[0],remark:'N'.repeat(26)}]),/không tự cắt/);assert.throws(()=>groupRows([{...rows[0],remark:'NỘP BHYT'}]),/không tự cắt/);
assert.throws(()=>groupRows([rows[0],{...rows[1],accountNumber:rows[0].accountNumber,remark:rows[0].remark}]),/không phân biệt/);
assert.equal(groupRows([{...rows[0],remark:''}])[0].options[0].remark,rows[0].paymentCode);
assert.equal(groupRows([{...rows[0],accountNumber:'1234567890123456789'}])[0].options[0].accountNumber,'1234567890123456789');assert.throws(()=>amount('781800.5'));assert.throws(()=>amount(0));assert.throws(()=>amount('-1'));assert.equal(amount('1,000,000'),1000000);
const many=groupRows([...rows,{...rows[0],label:'BHYT + dịch vụ',paymentCode:'HG26BH00125C',accountNumber:'000000000003',remark:'HG26BH00125C',amount:900000}]);const pages=paginate(many);assert.equal(pages.length,2);assert.deepEqual(pages.map(p=>p.visible.length),[2,1]);assert.equal(pages[1].choiceStart,2);assert.equal(pages[1].options.length,3);
assert.equal(groupRows([rows[0],{...rows[1],group:'DOT_KHAC'}]).length,2);
const context={Intl,Blob,TextEncoder,console,document:{querySelector(){}}};vm.createContext(context);const src=fs.readFileSync(require.resolve('../insurance.js'),'utf8');vm.runInContext(src.slice(0,src.indexOf('const norm='))+'globalThis.t={buildVietQrPayload,crc16ccitt,insurancePdf};})();',context);const t=context.t;
function tags(s){let i=0,out={};while(i<s.length){const id=s.slice(i,i+2),n=Number(s.slice(i+2,i+4));assert.ok(Number.isInteger(n)&&i+4+n<=s.length);out[id]=s.slice(i+4,i+4+n);i+=n+4;}return out;}
for(const o of groups[0].options){const payload=t.buildVietQrPayload(o,o.amount,o.remark),f=tags(payload);assert.equal(tags(tags(f['38'])['01'])['01'],o.accountNumber);assert.equal(f['54'],String(o.amount));assert.equal(tags(f['62'])['08'],o.remark);assert.equal(f['63'],t.crc16ccitt(payload.slice(0,-4)));}
const mixed={...groups[0].options[0],remark:'Test_001-A'};assert.equal(tags(tags(t.buildVietQrPayload(mixed,mixed.amount,mixed.remark))['62'])['08'],'Test_001-A');
console.log('PASS: grouping and pagination; distinct codes/accounts/amounts; ambiguous and duplicate records rejected; exact QR recipients/references and CRC.');
